// src/components/Nav.svelte
<script>
  import { githubAlt, linkedin, linkedinSquare } from "svelte-awesome/icons";
  import Icon from "svelte-awesome/components/Icon.svelte";
  $: toggle = false;
  $: border = "border-gray-600";
  $: activeAbout = "";
  $: activeResume = "";

  const handleMenuToggle = (e) => {
    // show menu below
    toggle = !toggle;
    if (toggle) {
      border = "border-red-600";
      return;
    }
    border = "border-gray-600";
  };

  const close = (menu = "") => {
    toggle = false;
    switch (menu) {
      case "about":
        activeAbout = "border-red-400";
        activeResume = "";
        break;
      case "resume":
        activeAbout = "";
        activeResume = "border-red-400";
        break;
      default:
        activeAbout = "";
        actoveResume = "";
        break;
    }
  };
</script>

<main>
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
  <style></style>
  <div class="flex-1 font-mono">
    <!-- NAVBAR -->

    <div
      class={`lg:px-6 py-2 my-2 px-4 border-b-2 ${border} flex justify-between`}
    >
      <div>
        <!-- <img width="50px" height="50px" src="https://logos-download.com/wp-content/uploads/2016/11/EA_logo_black.png" /> -->
        <h1 class="text-black  hover:text-red-500" on:click={() => close()}>
          <a class="a-no-style " href="/"> Gracias </a>
        </h1>
        <!-- show this section if theey click on the hamburger-->
        <div class="pt-3 hidden" id="menu">
          <nav class="cursor-pointer">
            <ul>
              <li class="border-transparent border-b-2 hover:border-gray-600">
                <a class="a-no-style" href="/about"> About </a>
              </li>
              <li class="border-transparent border-b-2 hover:border-gray-600">
                <a
                  class="a-no-style"
                  href="https://personal-foto.s3.us-west-1.amazonaws.com/resume.pdf"
                  download
                >
                  Resume
                </a>
              </li>
              <li>New list</li>
              <li class="border-transparent border-b-2 hover:border-gray-600">
                <Icon
                  data={githubAlt}
                  class="text-black-400 hover:text-black-700 bg-white"
                  scale="2"
                />
              </li>
              <li class="border-transparent border-b-2 hover:border-gray-600">
                <Icon
                  data={githubAlt}
                  class="text-black-400 hover:text-black-700 bg-white"
                  scale="2"
                />
              </li>
            </ul>
          </nav>
        </div>
      </div>
      <div class="inline lg:hidden mt-1 ml-2">
        <label on:click={handleMenuToggle}>
          {#if !toggle}
            <i class="fa fa-bars fa-lg cursor-pointer" />
          {:else if toggle}
            <i class="fa fa-times fa-lg cursor-pointer float-right" />
          {:else}{/if}
        </label>
      </div>
      <!-- <input type="checkbox" id="menu-toggle" class="mt-4 hidden" /> -->

      <div class="lg:block lg:float-right hidden cursor-pointer">
        <p
          class={`px-2 inline  border-transparent border-b-2  hover:border-red-400 ${activeAbout}`}
        >
          <a class="a-no-style" on:click={() => close("about")} href="/about"
            >About</a
          >
        </p>
        <p
          class="px-2 inline border-transparent border-b-2 hover:border-red-400"
        >
          <a
            target="_blank"
            class="a-no-style"
            href="https://personal-foto.s3.us-west-1.amazonaws.com/resume.pdf"
            download
          >
            Resume</a
          >
        </p>
        <p
          class=" px-1 border-transparent inline  border-b-2 bottom-1 relative hover:border-teal-600 focus:outline-none outline-none"
        >
          <a
            target="_blank"
            class="a-no-style"
            href="https://github.com/graciasc"
          >
            <Icon
              data={githubAlt}
              class="text-black-400 hover:text-gray-700 bg-white"
              scale="2"
            />
          </a>
        </p>
        <p
          class=" px-1 border-transparent inline  border-b-2 bottom-1 relative hover:border-teal-600 focus:outline-none outline-none"
        >
          <a
            target="_blank"
            class="a-no-style"
            href="https://www.linkedin.com/in/gracias-claude/"
          >
            <Icon
              href="https://www.linkedin.com/in/gracias-claude/"
              data={linkedinSquare}
              class="text-blue-600 hover:text-blue-800 bg-white"
              scale="2"
            />
          </a>
        </p>
      </div>
    </div>
  </div>
  {#if toggle === true}
    <div class="px-3 font-mono grid ">
      <nav class="cursor-pointer block">
        <ul>
          <li
            class={`table border-transparent border-b-2 hover:border-red-400 ${activeAbout}`}
          >
            <a on:click={() => close("about")} class="a-no-style" href="/about">
              About
            </a>
          </li>
          <li
            class={`table border-transparent border-b-2 hover:border-red-400 ${activeResume}`}
          >
            <a
              on:click={() => close()}
              target="_blank"
              class="a-no-style"
              href="https://personal-foto.s3.us-west-1.amazonaws.com/resume.pdf"
              download
            >
              Resume
            </a>
          </li>
        </ul>
      </nav>
    </div>
  {/if}
</main>

<style>
  .a-no-style {
    text-decoration: inherit;
    color: inherit;
    cursor: pointer;
  }
</style>

// app/components/Nav.tsx
import { useState } from "react";
import { Link } from "react-router";

export function Nav() {
  const [open, setOpen] = useState(false);
  const [active, setActive] = useState<"about" | "resume" | "">("");

  const border = open ? "border-red-600" : "border-gray-600";

  function close(menu: "about" | "resume" | "" = "") {
    setOpen(false);
    setActive(menu);
  }

  return (
    <main>
      <div className="flex-1 font-mono">
        <div className={`lg:px-6 py-2 my-2 px-4 border-b-2 ${border} flex justify-between`}>
          <div>
            <h1 className="text-black hover:text-red-500" onClick={() => close()}>
              <Link className="a-no-style" to="/">
                Gracias
              </Link>
            </h1>
          </div>

          <div className="inline lg:hidden mt-1 ml-2">
            <button
              type="button"
              className="bg-transparent border-0 p-0 m-0"
              aria-label="Toggle menu"
              onClick={() => setOpen((value) => !value)}
            >
              <i className={`fa ${open ? "fa-times float-right" : "fa-bars"} fa-lg cursor-pointer`} />
            </button>
          </div>

          <div className="lg:block lg:float-right hidden cursor-pointer">
            <p className={`px-2 inline border-transparent border-b-2 hover:border-red-400 ${active === "about" ? "border-red-400" : ""}`}>
              <Link className="a-no-style" onClick={() => close("about")} to="/about">
                About
              </Link>
            </p>
            <p className="px-2 inline border-transparent border-b-2 hover:border-red-400">
              <a target="_blank" rel="noreferrer" className="a-no-style" href="/images/graciasc.pdf" download>
                Resume
              </a>
            </p>
            <p className="px-1 border-transparent inline border-b-2 bottom-1 relative hover:border-teal-600 focus:outline-none outline-none">
              <a target="_blank" rel="noreferrer" className="a-no-style" href="https://github.com/graciasc" aria-label="GitHub">
                <i className="fa fa-github fa-2x text-black hover:text-gray-700 bg-white" />
              </a>
            </p>
            <p className="px-1 border-transparent inline border-b-2 bottom-1 relative hover:border-teal-600 focus:outline-none outline-none">
              <a target="_blank" rel="noreferrer" className="a-no-style" href="https://www.linkedin.com/in/gracias-claude/" aria-label="LinkedIn">
                <i className="fa fa-linkedin-square fa-2x text-blue-600 hover:text-blue-800 bg-white" />
              </a>
            </p>
          </div>
        </div>
      </div>

      {open && (
        <div className="px-3 font-mono grid">
          <nav className="cursor-pointer block">
            <ul>
              <li className={`table border-transparent border-b-2 hover:border-red-400 ${active === "about" ? "border-red-400" : ""}`}>
                <Link onClick={() => close("about")} className="a-no-style" to="/about">
                  About
                </Link>
              </li>
              <li className={`table border-transparent border-b-2 hover:border-red-400 ${active === "resume" ? "border-red-400" : ""}`}>
                <a onClick={() => close("resume")} target="_blank" rel="noreferrer" className="a-no-style" href="/images/graciasc.pdf" download>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
        </div>
      )}
    </main>
  );
}
