// app/routes/about.tsx
const skills = ["REACT", "JAVA", "JS", "CSS", "C++", "NODEJS", "SWIFT", "C", "C#"];

export function meta() {
  return [{ title: "About | Gracias Claude" }];
}

export default function About() {
  return (
    <main className="bg-white font-mono text-gray-900">
      <section className="mx-auto max-w-6xl px-6 py-16 lg:py-28">
        <div className="grid items-center gap-12 lg:grid-cols-[420px_1fr]">
          <div className="w-full">
            <img
              className="mx-auto aspect-square w-full max-w-80 rounded-3xl object-cover object-center shadow-lg lg:mx-0 lg:h-[420px] lg:w-[420px] lg:max-w-none"
              src="/images/gracias.jpg"
              alt="Gracias Claude profile"
            />
          </div>

          <div>
            <h1 className="text-5xl font-extrabold leading-tight tracking-tight lg:text-7xl">
              Hello World!
            </h1>
            <p className="mt-6 max-w-2xl text-xl leading-8 text-gray-700 lg:text-2xl">
              I have a desire to excel and continuously improve in my work. Learn more about my journey below.
            </p>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-20">
        <div className="grid gap-10 rounded-3xl bg-gray-50 p-8 shadow-sm lg:grid-cols-[1fr_420px] lg:p-12">
          <div>
            <h2 className="text-4xl font-extrabold leading-tight lg:text-6xl">
              My Career <br /> So Far!
            </h2>
            <p className="mt-6 max-w-3xl text-lg leading-8 text-gray-700">
              Always up for a challenge, I have worked for start-ups while attending University. Currently, I work as a Software Engineer for a widely innovative fintech company.
            </p>
          </div>

          <div className="flex flex-wrap content-start gap-3">
            {skills.map((skill) => (
              <span
                className="rounded-full border border-red-400 bg-white px-5 py-2 text-sm font-medium text-gray-700"
                key={skill}
              >
                {skill}
              </span>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}

// src/pages/About.svelte
<script>
  let pic = "image/gracias.jpg";
</script>

<main>
  <div class="bg-white lg:h-screen h-full font-mono">
    <!-- 1 COL -->
    <div
      class="lg:grid lg:grid-cols-1 lg:justify-center lg:mx-6 lg:mt-24 mt-12 mx-4 "
    >
      <!-- CONTAINERS  -->
      <div class="lg:grid lg:gap-6 lg:grid-cols-2 lg:rounded-lg  ">
        <div class="lg:aspect-h-1 lg:aspect-w-1 aspect-w-3 aspect-h-7">
          <div class="lg:flex lg:justify-end">
            <img
              class="object-cover shadow-md rounded-3xl lg:h-3/5 lg:w-3/6"
              src="images/gracias.jpg"
              alt="profile picture"
            />
          </div>
        </div>

        <div class="lg:w-3/4 lg:mt-6 -my-60">
          <h1 class="lg:text-7xl text-5xl font-bold text-center lg:text-left">
            Hello World!
          </h1>
          <p class="pt-4 lg:text-2xl">
             I have a desire to excel and continuously improve in my work. Learn more
            about my journey below.
          </p>
        </div>
      </div>
    </div>

    <div
      class="lg:flex rounded-lg lg:px-32 lg:-my-48  my-72 lg:ml-40 justify-center"
    >
      <div class="pt-4 lg:w-1/2  mb-12">
        <div class="grid lg:justify-end">
          <h1 class="lg:text-6xl  text-5xl font-bold lg:text-left text-center">
            My Career <br> So Far!
          </h1>
          <p class="pt-4 text-lg">
            Always up for a challenge, I have worked for start-ups at the same time doing University.
             Currently, I work as a Software Engineer for a widely innovative a fin-tech company.          </p>
        </div>
      </div>

      <div class=" mt-6 grid grid-cols-4 gap-2 h-0 text-center ">
        <div
          class="lg:flex lg:justify-center lg:items-center lg:m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            REACT
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 px-2 py-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            JAVA
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 px-2 py-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            JS
          </div>
        </div>

        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            CSS
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            C++
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            NODEJS
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            SWIFT
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            C
          </div>
        </div>
        <div
          class="flex justify-center items-center m-1 font-medium lg:py-1 py-2 px-2 bg-white rounded-full text-gray-700 bg-gray-150 border border-red-400 "
        >
          <!-- <div slot="avatar">
                  <div class="flex relative w-4 h-4 bg-orange-500 justify-center items-center m-1 mr-2 ml-0 my-0 text-xs rounded-full"><img class="rounded-full" alt="A" src="https://randomuser.me/api/portraits/women/68.jpg"> </div>
              </div> -->
          <div class="text-xs font-normal leading-none max-w-full flex-initial">
            C#
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
